# Project information
site_name: MLS800
site_description: An open-source MIDI controlled loop switcher
site_author: Bertrand Lemasle
site_url: https://blemasle.github.io/mls800/

# Repository
repo_name: 'blemasle/mls800-docs'
repo_url: 'https://github.com/blemasle/mls800-docs'

# Copyright
copyright: 'Copyright &copy; 2013 - 2019 <a href="https://github.com/blemasle">Bertrand Lemasle</a>'

# Configuration
theme: material

# Extensions
markdown_extensions:
  - meta
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: True

# Navigation
nav:
  - Home: 'index.md'
  - 'hardware.md'
  - 'building.md'
  - 'manual.md'
  - 'gallery.md'
  - 'history.md'
